"""Build the notebook pages — the project record as the human reads it.

Reads docs/record through project_record.py (which validates it) and writes
four pages into the notebook: the home page, the project record, the roadmap
board and the ideas catalogue. It also copies tools/assets (the theme, the
board's script and stylesheet) into the notebook's assets folder, so the
notebook works on any machine after one build. Standard library only.

    python tools/build_record.py          validate the record and rebuild stale pages and assets
    python tools/build_record.py --check  report stale pages and assets without writing
"""

from __future__ import annotations

import argparse
from datetime import date
from html import escape, unescape
import json
from pathlib import Path
import re
import sys

from project_record import CARD_STATUS, CONFIG, ID, NAME_LIMIT, RecordError, load, read_config, reversed_by

ID_PAGE = {"R": "roadmap.html", "D": "project-record.html", "IDEA": "ideas-catalogue.html"}
NAV = (("Notebook", "index.html"), ("Project record", "project-record.html"),
       ("Roadmap", "roadmap.html"), ("Ideas", "ideas-catalogue.html"))
DEV_LOG = ("Dev-log", "dev-log/dev-log.html")
ASSETS = Path(__file__).resolve().parent / "assets"  # travel with the tools; copied into the notebook by write_pages
# The files the pages link to. A build fails if one is absent from ASSETS.
THEME, BOARD_STYLE, BOARD_SCRIPT = REQUIRED_ASSETS = ("legend-theme.css", "roadmap-board.css", "roadmap-board.js")

# The words the reader sees that are not taken from the record. Page titles, the search tools and the board's
# dialogs hold their own static labels in the markup next to them (NAV, SEARCH, BOARD_DIALOG).
TEXT = {
    "user": "User decision", "agent": "Agent decision", "open": "Open question", "reversed": "Reversed",
    "idea_open": "Open", "idea_adopted": "Adopted", "idea_parked": "Parked", "idea_dropped": "Dropped",
    "origin_user": "Mine", "origin_agent": "AI proposal",
    "reason": "Why:", "alternatives": "Alternatives considered:", "roadmap": "Roadmap:",
    "reverses": "Reverses:", "reversed_by": "Reversed by:", "source": "Source:",
    "checkpoint": "Suggested checkpoint:", "research": "The research report", "dev_log": "The story in the dev-log",
    "record_lead": "The diary of decisions, reversals and open questions: what we chose, and why.",
    "ideas_lead": "Possibilities, including the ones that may never be built. "
                  "Nothing here is approved just because it is written down.",
    "board_lead": "What is planned, in progress, done and abandoned. Issues holds known problems. "
                  "A card in Research is researched at the next Claude session.",
    "manage": "Categories and flags",
    # Handed to assets/roadmap-board.js with the cards: every label the board script shows.
    "board_text": {
        "locked": "Read-only. Run the open-roadmap launcher in the project's tools folder to move, add or edit cards.",
        "open": "Drag a card to move it. Changes save straight away.",
        "report": "Read the report", "add_card": "+ Add card", "edit": "Edit",
        "saved": "Saved.", "not_saved": "Not saved: ",
        "opened": "Opened ", "revealed": "Shown in folder: ", "not_opened": "Not opened: ",
    },
    "waiting": "Waiting on your decision", "in_progress": "In progress", "latest": "Latest decisions",
    "reports": "Research", "more": "Read more", "nothing": "Nothing recorded yet.",
    "generated": "Built from <code>docs/record</code> by <code>tools/build_record.py</code>. "
                 "Do not edit this file by hand.",
}

SEARCH = """<div class="search-tools"><label for="search"><strong>%(label)s</strong></label>
<input id="search" type="search" placeholder="Type a word or two…" />
<p id="search-status" class="search-status" aria-live="polite"></p><div class="filters">%(filters)s</div></div>"""
SEARCH_SCRIPT = """<script>
(() => {
  const input = document.getElementById("search");
  const status = document.getElementById("search-status");
  const units = [...document.querySelectorAll(".search-unit")];
  const buttons = [...document.querySelectorAll("[data-filter]")];
  let filter = "all";
  const normal = (text) => text.toLocaleLowerCase().normalize("NFKD").replace(/[\\u0300-\\u036f]/g, "");
  function search() {
    const words = normal(input.value.trim()).split(/\\s+/).filter(Boolean);
    let count = 0;
    for (const unit of units) {
      const kind = filter === "all" || unit.dataset.kind.split(" ").includes(filter);
      unit.hidden = !(kind && words.every((word) => normal(unit.textContent).includes(word)));
      if (!unit.hidden) count++;
    }
    for (const button of buttons) button.setAttribute("aria-pressed", String(button.dataset.filter === filter));
    status.textContent = count + " of " + units.length + " shown.";
  }
  function clear() { input.value = ""; filter = "all"; search(); }
  input.addEventListener("input", search);
  for (const button of buttons) button.addEventListener("click", () => { filter = button.dataset.filter; search(); });
  function reveal() {
    const target = document.getElementById(decodeURIComponent(location.hash.slice(1)));
    if (target && target.closest("[hidden]")) { clear(); target.scrollIntoView({ block: "start" }); }
  }
  window.addEventListener("hashchange", reveal);
  search();
  if (location.hash) reveal();
})();
</script>"""

# The board's markup. assets/roadmap-board.js fills the selects, the flag boxes and the rows from the board data,
# and depends on the order here: "+ Add …" is the last child of its fieldset, and a row is name, colour, Remove.
BOARD_DIALOG = f"""<dialog id="card-dialog"><form method="dialog">
<label>Title<input name="title" required maxlength="200" /></label>
<label>Note — where it stands, the next step, or why it was abandoned<textarea name="note"></textarea></label>
<label>Column<select name="status"></select></label>
<label>Category<select name="category"><option value="">None</option></select></label>
<fieldset id="card-flags"><legend>Flags</legend></fieldset>
<label>Links and files — one per line<textarea name="links"></textarea></label>
<button type="button" value="cancel">Cancel</button> <button value="save">Save</button>
</form></dialog>
<dialog id="manage-dialog"><form method="dialog">
<fieldset data-list="categories"><legend>Categories</legend><button type="button">+ Add category</button></fieldset>
<fieldset data-list="flags"><legend>Flags</legend><button type="button">+ Add flag</button></fieldset>
<button type="button" value="cancel">Cancel</button> <button value="save">Save</button>
</form></dialog>
<template id="manage-row"><div class="manage-row">
<input required maxlength="{NAME_LIMIT}" pattern=".*\\S.*" aria-label="Name" />
<input type="color" value="#a6bdcb" aria-label="Colour" /><button type="button">Remove</button></div></template>"""


def human(iso: str) -> str:
    day = date.fromisoformat(iso)
    return f"{day.day} {day:%B %Y}"


def rich(text: str) -> str:
    """Escaped text, with `code` spans and record ids turned into links."""
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", escape(text, quote=False))
    return ID.sub(lambda match: f'<a href="{ID_PAGE[match[1]]}#{match[0]}">{match[0]}</a>', text)


def field(key: str, value) -> str:
    """One labelled line; nothing when the record has no value."""
    if not value:
        return ""
    return f"<p><strong>{TEXT[key]}</strong> {rich(', '.join(value) if isinstance(value, list) else value)}</p>"


def search_tools(label: str, filters: tuple) -> str:
    buttons = "".join(f'<button type="button" data-filter="{key}">{text}</button>' for key, text in filters)
    return SEARCH % {"label": label, "filters": buttons}


def record_page(data: dict) -> str:
    undone = reversed_by(data)
    entries = []
    for entry in data["record"][::-1]:
        kind = "open" if entry["status"] == "open" else "decided"
        badge = f'<span class="badge idea">{TEXT["open"]}</span>' if kind == "open" \
            else f'<span class="badge">{TEXT[entry["decided_by"]]}</span>'
        if entry["id"] in undone:
            kind += " reversed"
            badge += f' <span class="badge history">{TEXT["reversed"]}</span>'
        links = "".join(f'<p><a href="{escape(href, quote=True)}">{TEXT[key]}</a></p>' for key, href in (
            ("research", f"research/{entry.get('research')}.html"),
            ("dev_log", f"dev-log/dev-log.html#{entry.get('dev_log')}")) if key in entry)
        facts = "".join(field(key, entry.get(key)) for key in ("reason", "alternatives", "reverses", "roadmap"))
        entries.append(
            f'<article class="entry search-unit" data-kind="{kind}" id="{entry["id"]}"><div class="stamp">{entry["id"]}'
            f' · {human(entry["date"])} {badge}</div><h2>{rich(entry["title"])}</h2>'
            f'<p><strong>{rich(entry["summary"])}</strong></p><p>{rich(entry["decision"])}</p>'
            f'<div class="facts">{facts}{field("reversed_by", undone.get(entry["id"]))}{links}</div></article>')
    filters = (("all", "All"), ("open", "Open questions"), ("decided", "Decided"), ("reversed", "Reversed"))
    return (f"<p>{TEXT['record_lead']}</p>{search_tools('Find a decision', filters)}"
            f"{''.join(entries) or '<p>' + TEXT['nothing'] + '</p>'}{SEARCH_SCRIPT}")


def roadmap_page(data: dict) -> str:
    payload = {"columns": list(CARD_STATUS.items()), "cards": data["roadmap"], "board": data["board"],
               "text": TEXT["board_text"]}
    # "<" could end the script element early; JSON allows the escaped form.
    embedded = json.dumps(payload, ensure_ascii=False).replace("<", "\\u003c")
    return (f'<link rel="stylesheet" href="assets/{BOARD_STYLE}" /><p>{TEXT["board_lead"]}</p>'
            f'<p id="board-status" class="search-status" aria-live="polite"></p>'
            f'<p><button type="button" id="manage-open" hidden>{TEXT["manage"]}</button></p>'
            f'<div id="board"></div>{BOARD_DIALOG}<script type="application/json" id="board-data">{embedded}'
            f'</script><script src="assets/{BOARD_SCRIPT}"></script>')


def ideas_page(data: dict) -> str:
    ideas = "".join(
        f'<article class="idea search-unit" data-kind="{idea["origin"]}" id="{idea["id"]}"><div class="stamp">'
        f'{idea["id"]} · {TEXT["origin_" + idea["origin"]]} · {human(idea["date"])} <span class="status'
        f'{" parked" if idea["status"] in ("parked", "dropped") else ""}">{TEXT["idea_" + idea["status"]]}</span>'
        f'</div><h2>{rich(idea["title"])}</h2><p>{rich(idea["summary"])}</p><div class="facts">'
        f'{"".join(field(key, idea.get(key)) for key in ("source", "checkpoint", "roadmap"))}</div></article>'
        for idea in data["ideas"][::-1])
    filters = (("all", "All"), ("user", TEXT["origin_user"]), ("agent", TEXT["origin_agent"]))
    return (f"<p>{TEXT['ideas_lead']}</p>{search_tools('Find an idea', filters)}"
            f"{ideas or '<p>' + TEXT['nothing'] + '</p>'}{SEARCH_SCRIPT}")


def research_reports(notebook: Path) -> list[tuple[str, str]]:
    """(file name, page title) of each research report, newest first by file name. Both are plain text."""
    reports = []
    for path in sorted((notebook / "research").glob("*.html"), reverse=True):
        if path.stem != "research-template":
            title = re.search(r"<title>(.*?)</title>", path.read_text(encoding="utf-8"), re.S)
            reports.append((path.name, unescape(title[1].strip()) if title else path.stem))
    return reports


def index_page(config: dict, data: dict, nav: tuple) -> str:
    def section(key: str, items: list[str]) -> str:
        return f"<h2>{TEXT[key]}</h2><ul>{''.join(f'<li>{item}</li>' for item in items)}</ul>" if items else ""
    decided = [entry for entry in data["record"] if entry["status"] == "decided"][::-1][:5]
    undone = reversed_by(data)
    return (
        f"<p>{escape(config['tagline'])}</p>"
        + section("waiting", [f'<a href="project-record.html#{entry["id"]}">{entry["id"]}</a> — {rich(entry["summary"])}'
                              for entry in data["record"] if entry["status"] == "open"])
        + section("in_progress", [f"{rich(card['id'])} — {rich(card['title'])}"
                                  + (f"<br />{rich(card['note'])}" if "note" in card else "")
                                  for card in data["roadmap"] if card["status"] == "in_progress"])
        + section("latest", [f'<a href="project-record.html#{entry["id"]}">{entry["id"]}</a> · '
                             f'{human(entry["date"])} — {rich(entry["summary"])}'
                             + (f' <span class="badge history">{TEXT["reversed"]}</span>' if entry["id"] in undone else "")
                             for entry in decided])
        + section("reports", [f'<a href="research/{escape(name, quote=True)}">{escape(title)}</a>'
                              for name, title in research_reports(config["notebook"])])
        + section("more", [f'<a href="{href}">{label}</a>' for label, href in nav[1:]]))


def build(config: dict, data: dict) -> dict[str, str]:
    nav = NAV + ((DEV_LOG,) if (config["notebook"] / DEV_LOG[1]).is_file() else ())
    project = escape(config["project"])
    bodies = {
        "index.html": ("Notebook", index_page(config, data, nav)),
        "project-record.html": ("Project record", record_page(data)),
        "roadmap.html": ("Roadmap", roadmap_page(data)),
        "ideas-catalogue.html": ("Ideas catalogue", ideas_page(data)),
    }
    links = " · ".join(f'<a href="{href}">{label}</a>' for label, href in nav)
    return {name: (
        "<!doctype html>\n<!-- Generated by tools/build_record.py from docs/record. Do not edit. -->\n"
        f'<html lang="en"><head><meta charset="utf-8" />'
        f'<meta name="viewport" content="width=device-width,initial-scale=1" />'
        f'<title>{project} · {title}</title><link rel="stylesheet" href="assets/{THEME}" /></head>\n'
        f'<body><nav>{links}</nav><p class="chapter">{project}</p><h1>{title}</h1>\n{body}\n'
        f'<p class="foot">{TEXT["generated"]}</p></body></html>\n'
    ) for name, (title, body) in bodies.items()}


def assets(notebook: Path) -> dict[Path, bytes]:
    """The notebook's assets folder as it should be: a copy of every file in the tools' assets folder."""
    for name in REQUIRED_ASSETS:
        if not (ASSETS / name).is_file():
            raise RecordError(f"{ASSETS / name} is missing; copy the tools folder again from the emzakit plugin")
    return {notebook / "assets" / path.name: path.read_bytes() for path in ASSETS.iterdir() if path.is_file()}


def write_pages(config: dict, check: bool = False) -> int:
    """Validate the record and rewrite the pages and assets that changed. Returns how many were stale."""
    pages = {config["notebook"] / name: text.encode("utf-8") for name, text in build(config, load(config)).items()}
    pages.update(assets(config["notebook"]))
    # The notebook folder itself may be a link (into a vault). Nothing inside it is written through one:
    # a cloned project could otherwise point a page at any file this user can write.
    for path in (config["notebook"] / "assets", *pages):
        if path.is_symlink():
            raise RecordError(f"{path} is a symbolic link; the builder does not write through one")
    stale = [path for path, content in pages.items() if not path.is_file() or path.read_bytes() != content]
    if check and stale:
        raise RecordError("Notebook files are stale. Run: python tools/build_record.py")
    for path in stale:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(pages[path])
    return len(stale)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="Validate the record and report stale files without writing")
    parser.add_argument("--config", type=Path, default=CONFIG, help="Project name and folder locations")
    options = parser.parse_args()
    try:
        stale = write_pages(read_config(options.config.resolve()), options.check)
        print(f"Record is valid. {stale} notebook file(s) rebuilt.")
        return 0
    except (RecordError, OSError, UnicodeError) as error:
        print(f"Record build failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
