"""Build the notebook pages — the project record as the human reads it.

Reads docs/record through project_record.py (which validates it) and writes
four pages into the notebook: the home page, the project record, the roadmap
board and the ideas catalogue. Standard library only.

    python tools/build_record.py          validate the record and rebuild stale pages
    python tools/build_record.py --check  report stale pages without writing
"""

from __future__ import annotations

import argparse
from datetime import date
from html import escape
import json
from pathlib import Path
import re
import sys

from project_record import CARD_STATUS, CONFIG, ID, RecordError, load, read_config, reversed_by

ID_PAGE = {"R": "roadmap.html", "D": "project-record.html", "IDEA": "ideas-catalogue.html"}
NAV = (("Notebook", "index.html"), ("Project record", "project-record.html"),
       ("Roadmap", "roadmap.html"), ("Ideas", "ideas-catalogue.html"))
DEV_LOG = ("Dev-log", "dev-log/dev-log.html")

# Every word the reader sees that is not taken from the record.
TEXT = {
    "user": "User decision", "agent": "Agent decision", "open": "Open question", "reversed": "Reversed",
    "idea_open": "Open", "idea_adopted": "Adopted", "idea_parked": "Parked", "idea_dropped": "Dropped",
    "origin_user": "Mine", "origin_agent": "AI proposal",
    "reason": "Why:", "alternatives": "Alternatives considered:", "roadmap": "Roadmap:",
    "reverses": "Reverses:", "reversed_by": "Reversed by:", "source": "Source:",
    "checkpoint": "Suggested checkpoint:", "research": "The research report", "dev_log": "The story in the dev-log",
    "record_lead": "The diary of decisions, reversals and open questions: what we chose, and why.",
    "ideas_lead": "Possibilities, including the ones that may never be built. "
                  "Nothing here is approved just because it is written down.",
    "board_lead": "What is planned, in progress, done and abandoned. Issues holds known problems. "
                  "A card in Research is researched at the next Claude session.",
    "report": "Read the report",
    "board_locked": "Read-only. Double-click open-roadmap.bat in the notebook folder to move, add or edit cards.",
    "board_open": "Drag a card to move it. Changes save straight away.",
    "waiting": "Waiting on your decision", "in_progress": "In progress", "latest": "Latest decisions",
    "reports": "Research", "more": "Read more", "nothing": "Nothing recorded yet.",
    "generated": "Built from <code>docs/record</code> by <code>tools/build_record.py</code>. "
                 "Do not edit this file by hand.",
}

SEARCH = """<div class="search-tools"><label for="search"><strong>%(label)s</strong></label>
<input id="search" type="search" placeholder="Type a word or two…" />
<p id="search-status" class="search-status" aria-live="polite"></p><div class="filters">%(filters)s</div></div>"""
SEARCH_SCRIPT = """<script>
(() => {
  const input = document.getElementById("search");
  const status = document.getElementById("search-status");
  const units = [...document.querySelectorAll(".search-unit")];
  const buttons = [...document.querySelectorAll("[data-filter]")];
  let filter = "all";
  const normal = (text) => text.toLocaleLowerCase().normalize("NFKD").replace(/[\\u0300-\\u036f]/g, "");
  function search() {
    const words = normal(input.value.trim()).split(/\\s+/).filter(Boolean);
    let count = 0;
    for (const unit of units) {
      const kind = filter === "all" || unit.dataset.kind.split(" ").includes(filter);
      unit.hidden = !(kind && words.every((word) => normal(unit.textContent).includes(word)));
      if (!unit.hidden) count++;
    }
    for (const button of buttons) button.setAttribute("aria-pressed", String(button.dataset.filter === filter));
    status.textContent = count + " of " + units.length + " shown.";
  }
  function clear() { input.value = ""; filter = "all"; search(); }
  input.addEventListener("input", search);
  for (const button of buttons) button.addEventListener("click", () => { filter = button.dataset.filter; search(); });
  function reveal() {
    const target = document.getElementById(decodeURIComponent(location.hash.slice(1)));
    if (target && target.closest("[hidden]")) { clear(); target.scrollIntoView({ block: "start" }); }
  }
  window.addEventListener("hashchange", reveal);
  search();
  if (location.hash) reveal();
})();
</script>"""

BOARD_STYLE = """<style>
  body { max-width: none; margin: 44px 32px; }
  #board { display: grid; grid-template-columns: repeat(auto-fit, minmax(230px, 1fr)); gap: 18px; align-items: start; }
  .column { border: 1px solid var(--line); border-radius: 10px; padding: 14px; min-height: 180px; }
  .column.over { border-color: var(--gold); }
  .column h2 { font: 650 17px/1.3 var(--body); letter-spacing: 0; margin: 0 0 12px; }
  .column h2 span { color: var(--muted); font-weight: 400; }
  .card { border: 1px solid var(--line); border-radius: 8px; padding: 12px 14px; margin: 0 0 10px; }
  .card[draggable="true"] { cursor: grab; }
  .card.dragging { opacity: .4; }
  .card h3 { font: 650 15px/1.4 var(--body); margin: 4px 0; }
  .card p { font-size: 14px; line-height: 1.5; margin: 6px 0 0; }
  .card button, .column > button { font-size: 12px; padding: 5px 12px; margin-top: 10px; }
  dialog { background: var(--night); color: var(--text); border: 1px solid var(--line); border-radius: 10px;
           padding: 24px; width: min(520px, 92vw); }
  dialog::backdrop { background: rgba(0, 0, 0, .7); }
  dialog label { display: block; margin: 0 0 14px; font-size: 14px; }
  dialog input, dialog textarea, dialog select { display: block; width: 100%; margin-top: 6px; padding: 10px 12px;
           border: 1px solid var(--line); border-radius: 8px; background: var(--surface); color: var(--heading); }
  dialog textarea { min-height: 110px; font: 15px/1.5 var(--body); }
</style>"""
BOARD_DIALOG = """<dialog id="card-dialog"><form method="dialog">
<label>Title<input name="title" required maxlength="200" /></label>
<label>Note — where it stands, the next step, or why it was abandoned<textarea name="note"></textarea></label>
<label>Column<select name="status"></select></label>
<button value="cancel" formnovalidate>Cancel</button> <button value="save">Save</button>
</form></dialog>"""


def human(iso: str) -> str:
    day = date.fromisoformat(iso)
    return f"{day.day} {day:%B %Y}"


def rich(text: str) -> str:
    """Escaped text, with `code` spans and record ids turned into links."""
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", escape(text, quote=False))
    return ID.sub(lambda match: f'<a href="{ID_PAGE[match[1]]}#{match[0]}">{match[0]}</a>', text)


def field(key: str, value) -> str:
    """One labelled line; nothing when the record has no value."""
    if not value:
        return ""
    return f"<p><strong>{TEXT[key]}</strong> {rich(', '.join(value) if isinstance(value, list) else value)}</p>"


def search_tools(label: str, filters: tuple) -> str:
    buttons = "".join(f'<button type="button" data-filter="{key}">{text}</button>' for key, text in filters)
    return SEARCH % {"label": label, "filters": buttons}


def record_page(data: dict) -> str:
    undone = reversed_by(data)
    entries = []
    for entry in data["record"][::-1]:
        kind = "open" if entry["status"] == "open" else "decided"
        badge = f'<span class="badge idea">{TEXT["open"]}</span>' if kind == "open" \
            else f'<span class="badge">{TEXT[entry["decided_by"]]}</span>'
        if entry["id"] in undone:
            kind += " reversed"
            badge += f' <span class="badge history">{TEXT["reversed"]}</span>'
        links = "".join(f'<p><a href="{href}">{TEXT[key]}</a></p>' for key, href in (
            ("research", f"research/{entry.get('research')}.html"),
            ("dev_log", f"dev-log/dev-log.html#{entry.get('dev_log')}")) if key in entry)
        facts = "".join(field(key, entry.get(key)) for key in ("reason", "alternatives", "reverses", "roadmap"))
        entries.append(
            f'<article class="entry search-unit" data-kind="{kind}" id="{entry["id"]}"><div class="stamp">{entry["id"]}'
            f' · {human(entry["date"])} {badge}</div><h2>{rich(entry["title"])}</h2>'
            f'<p><strong>{rich(entry["summary"])}</strong></p><p>{rich(entry["decision"])}</p>'
            f'<div class="facts">{facts}{field("reversed_by", undone.get(entry["id"]))}{links}</div></article>')
    filters = (("all", "All"), ("open", "Open questions"), ("decided", "Decided"), ("reversed", "Reversed"))
    return (f"<p>{TEXT['record_lead']}</p>{search_tools('Find a decision', filters)}"
            f"{''.join(entries) or '<p>' + TEXT['nothing'] + '</p>'}{SEARCH_SCRIPT}")


def roadmap_page(data: dict) -> str:
    payload = {"columns": list(CARD_STATUS.items()), "cards": data["roadmap"],
               "locked": TEXT["board_locked"], "open": TEXT["board_open"], "report": TEXT["report"]}
    # "<" could end the script element early; JSON allows the escaped form.
    embedded = json.dumps(payload, ensure_ascii=False).replace("<", "\\u003c")
    return (f'{BOARD_STYLE}<p>{TEXT["board_lead"]}</p><p id="board-status" class="search-status" aria-live="polite">'
            f'</p><div id="board"></div>{BOARD_DIALOG}<script type="application/json" id="board-data">{embedded}'
            f'</script><script src="assets/roadmap-board.js"></script>')


def ideas_page(data: dict) -> str:
    ideas = "".join(
        f'<article class="idea search-unit" data-kind="{idea["origin"]}" id="{idea["id"]}"><div class="stamp">'
        f'{idea["id"]} · {TEXT["origin_" + idea["origin"]]} · {human(idea["date"])} <span class="status'
        f'{" parked" if idea["status"] in ("parked", "dropped") else ""}">{TEXT["idea_" + idea["status"]]}</span>'
        f'</div><h2>{rich(idea["title"])}</h2><p>{rich(idea["summary"])}</p><div class="facts">'
        f'{"".join(field(key, idea.get(key)) for key in ("source", "checkpoint", "roadmap"))}</div></article>'
        for idea in data["ideas"][::-1])
    filters = (("all", "All"), ("user", TEXT["origin_user"]), ("agent", TEXT["origin_agent"]))
    return (f"<p>{TEXT['ideas_lead']}</p>{search_tools('Find an idea', filters)}"
            f"{ideas or '<p>' + TEXT['nothing'] + '</p>'}{SEARCH_SCRIPT}")


def research_reports(notebook: Path) -> list[tuple[str, str]]:
    """(file name, page title) of each research report, newest first by file name."""
    reports = []
    for path in sorted((notebook / "research").glob("*.html"), reverse=True):
        if path.stem != "research-template":
            title = re.search(r"<title>(.*?)</title>", path.read_text(encoding="utf-8"), re.S)
            reports.append((path.name, title[1].strip() if title else escape(path.stem)))
    return reports


def index_page(config: dict, data: dict, nav: tuple) -> str:
    def section(key: str, items: list[str]) -> str:
        return f"<h2>{TEXT[key]}</h2><ul>{''.join(f'<li>{item}</li>' for item in items)}</ul>" if items else ""
    decided = [entry for entry in data["record"] if entry["status"] == "decided"][::-1][:5]
    undone = reversed_by(data)
    return (
        f"<p>{escape(config['tagline'])}</p>"
        + section("waiting", [f'<a href="project-record.html#{entry["id"]}">{entry["id"]}</a> — {rich(entry["summary"])}'
                              for entry in data["record"] if entry["status"] == "open"])
        + section("in_progress", [f"{rich(card['id'])} — {rich(card['title'])}"
                                  + (f"<br />{rich(card['note'])}" if "note" in card else "")
                                  for card in data["roadmap"] if card["status"] == "in_progress"])
        + section("latest", [f'<a href="project-record.html#{entry["id"]}">{entry["id"]}</a> · '
                             f'{human(entry["date"])} — {rich(entry["summary"])}'
                             + (f' <span class="badge history">{TEXT["reversed"]}</span>' if entry["id"] in undone else "")
                             for entry in decided])
        + section("reports", [f'<a href="research/{name}">{title}</a>'
                              for name, title in research_reports(config["notebook"])])
        + section("more", [f'<a href="{href}">{label}</a>' for label, href in nav[1:]]))


def build(config: dict, data: dict) -> dict[str, str]:
    nav = NAV + ((DEV_LOG,) if (config["notebook"] / DEV_LOG[1]).is_file() else ())
    project = escape(config["project"])
    bodies = {
        "index.html": ("Notebook", index_page(config, data, nav)),
        "project-record.html": ("Project record", record_page(data)),
        "roadmap.html": ("Roadmap", roadmap_page(data)),
        "ideas-catalogue.html": ("Ideas catalogue", ideas_page(data)),
    }
    links = " · ".join(f'<a href="{href}">{label}</a>' for label, href in nav)
    return {name: (
        "<!doctype html>\n<!-- Generated by tools/build_record.py from docs/record. Do not edit. -->\n"
        f'<html lang="en"><head><meta charset="utf-8" />'
        f'<meta name="viewport" content="width=device-width,initial-scale=1" />'
        f'<title>{project} · {title}</title><link rel="stylesheet" href="assets/legend-theme.css" /></head>\n'
        f'<body><nav>{links}</nav><p class="chapter">{project}</p><h1>{title}</h1>\n{body}\n'
        f'<p class="foot">{TEXT["generated"]}</p></body></html>\n'
    ) for name, (title, body) in bodies.items()}


def write_pages(config: dict, check: bool = False) -> int:
    """Validate the record and rewrite the pages that changed. Returns how many were stale."""
    pages = {config["notebook"] / name: text.encode("utf-8") for name, text in build(config, load(config)).items()}
    stale = [path for path, content in pages.items() if not path.is_file() or path.read_bytes() != content]
    if check and stale:
        raise RecordError("Notebook pages are stale. Run: python tools/build_record.py")
    for path in stale:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(pages[path])
    return len(stale)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="Validate the record and report stale pages without writing")
    parser.add_argument("--config", type=Path, default=CONFIG, help="Project name and folder locations")
    options = parser.parse_args()
    try:
        stale = write_pages(read_config(options.config.resolve()), options.check)
        print(f"Record is valid. {stale} notebook page(s) rebuilt.")
        return 0
    except (RecordError, OSError, UnicodeError) as error:
        print(f"Record build failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
